### ISSUE TITLE
Unable to load theme

### ISSUE THREAD

**Issue by ghost** [Chemaclass/knob-base#5]
Hello, I tried your project, but get this error: 

`Warning: require(/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/config/config.php): failed to open stream: Invalid argument in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\libs\Utils.php on line 63`

How to solve it?

Thanks in advance.

**Comment by Chemaclass** [comment]
@wordpressseo6  Hi! That seems to be that you don't have the config file (knob-mvc/app/config.php) or you don't have the rights to read it. The error log says that the "required $file failed to open stream". Take a look there, you should have something like this https://github.com/Chemaclass/knob-mvc/blob/master/app/config/config.php then check for the permissions and tell me :)

**Comment by Chemaclass** [comment]
@wordpressseo6 I made an update, now the config file is optional. So, now if you dont have this file, your template wont break anymore. Tell me if works in order to close the Issue. Thanks!

**Comment by wordpressseo6** [comment]
Hello, thanks for response. Unfortunally i have update knob-mvc + knob-base but the problem persist.

In app/config the file config.php is present.  Any idea for solving this issue?

**Comment by ghost** [comment]
After updating i obtain a new error;

`Warning: array_keys() expects parameter 1 to be array, null given in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 46`

`Warning: session_start(): Cannot send session cookie - headers already sent by (output started at C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php:46) in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 79`

`Notice: Undefined index: current-lang in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 79`

`Warning: in_array() expects parameter 2 to be array, null given in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 72`

... and many more
The app/config/config.php is present

**Comment by Chemaclass** [comment]
@wordpressseo6 Update your knob-base using composer. And tell me if you still have this error :)

**Comment by ghost** [comment]
Hello, updating but not solving.

`Notice: Undefined index: current-lang in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 79`

`Notice: Undefined offset: 1 in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 135`

`Warning: require(/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/i18n/en/global.php): failed to open stream: Invalid argument in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 167`

`Fatal error: require(): Failed opening required '/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/i18n/en/global.php' (include_path='.;C:\php\pear') in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 167`

**Comment by Chemaclass** [comment]
@wordpressseo6 seems interesting. I pushed some commits where are suppose to solve the first two warnings.  About the other two ones...

`
Warning: require(/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/i18n/en/global.php): failed to open stream: Invalid argument in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 167
`
`
Fatal error: require(): Failed opening required '/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/i18n/en/global.php' (include_path='.;C:\php\pear') in C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master\vendor\chemaclass\knob-base\src\i18n\I18n.php on line 167
`

The error is pretty clear: "failed to open stream" / "Failed opening required". Are you sure that you have this file? also with the correct permissions? (read by apache, at least) `/C:\wamp64\www\wordpress1\wp-content\themes\knob-mvc-master/app/i18n/en/global.php`

Anyway, update the knob-base again, and please tell me if the problem was solve or copy&paste here the next error so I can figure it out how to solve it :)
Tell me also, please, your PHP version, thanks!

**Comment by ghost** [comment]
Ok now work fine but only with debug constant set to false. If set true not work and show more error.

My php version is 7.0.10 on desktop and 5.26.5 on laptop.

The framework uses some css that changes the control panel?
This screen is before activating theme
![before](https://cloud.githubusercontent.com/assets/14064365/22866138/55a115f8-f171-11e6-84cb-3e796c68bc77.PNG)


This screen is after activating theme
![after](https://cloud.githubusercontent.com/assets/14064365/22866140/582f3c32-f171-11e6-8c2a-5f8336bc8aa7.PNG)

**Comment by Chemaclass** [comment]
I completely forgot about the WP_DEBUG const. You are right, if is true then a few warning are displayed; I will work on it in order to avoid them :)

**Comment by Chemaclass** [comment]
About "The framework uses some css that changes the control panel?" Yes, the stylish is appied to frontend and also to the backend (control panel). I didn't focus on stylish when I was working on this project, because my goal was build and prepare the structure, so the style is something that the devs need to care and not the framework itself.
If you take a look into `sass-css/main.scss` file you will see: 
```
body, #wpwrap {
	background-color: $body-background-color;
	color: $body-color;
	font-family: Helvetica,Arial;
	font-size: 16px;
}
```
I think you got the idea :)

**Comment by ghost** [comment]
Thanks for the answers. For css in backend I'll try to arrange it somehow.

See you soon and thanks for Framewok.

**Comment by Chemaclass** [comment]
@wordpressseo6 I also fixed the warnings coming from Wordpress when you have the flag WP_DEBUG = true.
